"""Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms."""


def main():
    print(solve(4000000))


def solve(number):
    fib_seq = fib(number)
    even_fib_seq = filter(lambda x: x % 2 == 0, fib_seq)
    return sum(even_fib_seq)


def fib(max_term):
    x, y = 1, 1
    yield x
    yield y
    while x + y <= max_term:
        x, y = y, x + y
        yield y


if __name__ == "__main__":
    main()